[workspace]
authors = ["Nigel Sjolin Grech <nigelgrech.ng@gmail.com>"]
channels = ["conda-forge"]
name = "UBISS-2025-workshop-pix-2-psych"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pandas = ">=2.3.0,<3"
numpy = ">=2.3.0,<3"
scipy = ">=1.15.2,<2"
scikit-learn = ">=1.7.0,<2"
pyyaml = ">=6.0.2,<7"
googlemaps = ">=4.10.0,<5"
geopy = ">=2.4.1,<3"
matplotlib = ">=3.10.3,<4"
astropy = ">=7.1.0,<8"
pytz = ">=2025.2,<2026"
pixi-pycharm = ">=0.0.8,<0.0.9"
python-dotenv = ">=1.1.0,<2"
mysql = ">=9.3.0,<10"
mysql-connector-python = ">=9.3.0,<10"
pymysql = ">=1.1.1,<2"
sqlalchemy = ">=2.0.41,<3"
flask = ">=3.1.1,<4"
openai = ">=1.86.0,<2"
